//! Neo VM OpCodes - Based on Neo N3 specification

/// Neo VM Operation Codes
///
/// Names follow the official Neo N3 specification exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
#[allow(non_camel_case_types, missing_docs)]
pub enum OpCode {
    // Constants
    PUSHINT8 = 0x00,
    PUSHINT16 = 0x01,
    PUSHINT32 = 0x02,
    PUSHINT64 = 0x03,
    PUSHINT128 = 0x04,
    PUSHINT256 = 0x05,
    PUSHA = 0x0A,
    PUSHNULL = 0x0B,
    PUSHDATA1 = 0x0C,
    PUSHDATA2 = 0x0D,
    PUSHDATA4 = 0x0E,
    PUSHM1 = 0x0F,
    PUSH0 = 0x10,
    PUSH1 = 0x11,
    PUSH2 = 0x12,
    PUSH3 = 0x13,
    PUSH4 = 0x14,
    PUSH5 = 0x15,
    PUSH6 = 0x16,
    PUSH7 = 0x17,
    PUSH8 = 0x18,
    PUSH9 = 0x19,
    PUSH10 = 0x1A,
    PUSH11 = 0x1B,
    PUSH12 = 0x1C,
    PUSH13 = 0x1D,
    PUSH14 = 0x1E,
    PUSH15 = 0x1F,
    PUSH16 = 0x20,

    // Flow control
    NOP = 0x21,
    JMP = 0x22,
    JMP_L = 0x23,
    JMPIF = 0x24,
    JMPIF_L = 0x25,
    JMPIFNOT = 0x26,
    JMPIFNOT_L = 0x27,
    JMPEQ = 0x28,
    JMPEQ_L = 0x29,
    JMPNE = 0x2A,
    JMPNE_L = 0x2B,
    JMPGT = 0x2C,
    JMPGT_L = 0x2D,
    JMPGE = 0x2E,
    JMPGE_L = 0x2F,
    JMPLT = 0x30,
    JMPLT_L = 0x31,
    JMPLE = 0x32,
    JMPLE_L = 0x33,
    CALL = 0x34,
    CALL_L = 0x35,
    CALLA = 0x36,
    CALLT = 0x37,
    ABORT = 0x38,
    ASSERT = 0x39,
    THROW = 0x3A,
    TRY = 0x3B,
    TRY_L = 0x3C,
    ENDTRY = 0x3D,
    ENDTRY_L = 0x3E,
    ENDFINALLY = 0x3F,
    RET = 0x40,
    SYSCALL = 0x41,

    // Stack operations
    DEPTH = 0x43,
    DROP = 0x45,
    NIP = 0x46,
    XDROP = 0x48,
    CLEAR = 0x49,
    DUP = 0x4A,
    OVER = 0x4B,
    PICK = 0x4D,
    TUCK = 0x4E,
    SWAP = 0x50,
    ROT = 0x51,
    ROLL = 0x52,
    REVERSE3 = 0x53,
    REVERSE4 = 0x54,
    REVERSEN = 0x55,

    // Slot operations
    INITSSLOT = 0x56,
    INITSLOT = 0x57,
    LDSFLD0 = 0x58,
    LDSFLD1 = 0x59,
    LDSFLD2 = 0x5A,
    LDSFLD3 = 0x5B,
    LDSFLD4 = 0x5C,
    LDSFLD5 = 0x5D,
    LDSFLD = 0x5E,
    STSFLD0 = 0x5F,
    STSFLD1 = 0x60,
    STSFLD2 = 0x61,
    STSFLD3 = 0x62,
    STSFLD4 = 0x63,
    STSFLD5 = 0x64,
    STSFLD = 0x65,
    LDLOC0 = 0x66,
    LDLOC1 = 0x67,
    LDLOC2 = 0x68,
    LDLOC3 = 0x69,
    LDLOC4 = 0x6A,
    LDLOC5 = 0x6B,
    LDLOC = 0x6C,
    STLOC0 = 0x6D,
    STLOC1 = 0x6E,
    STLOC2 = 0x6F,
    STLOC3 = 0x70,
    STLOC4 = 0x71,
    STLOC5 = 0x72,
    STLOC = 0x73,
    LDARG0 = 0x74,
    LDARG1 = 0x75,
    LDARG2 = 0x76,
    LDARG3 = 0x77,
    LDARG4 = 0x78,
    LDARG5 = 0x79,
    LDARG = 0x7A,
    STARG0 = 0x7B,
    STARG1 = 0x7C,
    STARG2 = 0x7D,
    STARG3 = 0x7E,
    STARG4 = 0x7F,
    STARG5 = 0x80,
    STARG = 0x81,

    // Splice operations
    NEWBUFFER = 0x88,
    MEMCPY = 0x89,
    CAT = 0x8B,
    SUBSTR = 0x8C,
    LEFT = 0x8D,
    RIGHT = 0x8E,

    // Bitwise operations
    INVERT = 0x90,
    AND = 0x91,
    OR = 0x92,
    XOR = 0x93,
    EQUAL = 0x97,
    NOTEQUAL = 0x98,

    // Arithmetic
    SIGN = 0x99,
    ABS = 0x9A,
    NEGATE = 0x9B,
    INC = 0x9C,
    DEC = 0x9D,
    ADD = 0x9E,
    SUB = 0x9F,
    MUL = 0xA0,
    DIV = 0xA1,
    MOD = 0xA2,
    POW = 0xA3,
    SQRT = 0xA4,
    MODMUL = 0xA5,
    MODPOW = 0xA6,
    SHL = 0xA8,
    SHR = 0xA9,
    NOT = 0xAA,
    BOOLAND = 0xAB,
    BOOLOR = 0xAC,
    NZ = 0xB1,
    NUMEQUAL = 0xB3,
    NUMNOTEQUAL = 0xB4,
    LT = 0xB5,
    LE = 0xB6,
    GT = 0xB7,
    GE = 0xB8,
    MIN = 0xB9,
    MAX = 0xBA,
    WITHIN = 0xBB,

    // Compound types
    PACKMAP = 0xBE,
    PACKSTRUCT = 0xBF,
    PACK = 0xC0,
    UNPACK = 0xC1,
    NEWARRAY0 = 0xC2,
    NEWARRAY = 0xC3,
    NEWARRAY_T = 0xC4,
    NEWSTRUCT0 = 0xC5,
    NEWSTRUCT = 0xC6,
    NEWMAP = 0xC8,
    SIZE = 0xCA,
    HASKEY = 0xCB,
    KEYS = 0xCC,
    VALUES = 0xCD,
    PICKITEM = 0xCE,
    APPEND = 0xCF,
    SETITEM = 0xD0,
    REVERSEITEMS = 0xD1,
    REMOVE = 0xD2,
    CLEARITEMS = 0xD3,
    POPITEM = 0xD4,

    // Types
    ISNULL = 0xD8,
    ISTYPE = 0xD9,
    TYPE = 0xDA,
    CONVERT = 0xDB,
    ABORTMSG = 0xE0,
    ASSERTMSG = 0xE1,

    // Crypto operations
    SHA256 = 0xF0,
    RIPEMD160 = 0xF1,
    HASH160 = 0xF2,
    CHECKSIG = 0xF3,
}

impl TryFrom<u8> for OpCode {
    type Error = String;

    fn try_from(byte: u8) -> Result<Self, Self::Error> {
        match byte {
            0x00 => Ok(OpCode::PUSHINT8),
            0x01 => Ok(OpCode::PUSHINT16),
            0x02 => Ok(OpCode::PUSHINT32),
            0x03 => Ok(OpCode::PUSHINT64),
            0x04 => Ok(OpCode::PUSHINT128),
            0x05 => Ok(OpCode::PUSHINT256),
            0x0A => Ok(OpCode::PUSHA),
            0x0B => Ok(OpCode::PUSHNULL),
            0x0C => Ok(OpCode::PUSHDATA1),
            0x0D => Ok(OpCode::PUSHDATA2),
            0x0E => Ok(OpCode::PUSHDATA4),
            0x0F => Ok(OpCode::PUSHM1),
            0x10 => Ok(OpCode::PUSH0),
            0x11 => Ok(OpCode::PUSH1),
            0x12 => Ok(OpCode::PUSH2),
            0x13 => Ok(OpCode::PUSH3),
            0x14 => Ok(OpCode::PUSH4),
            0x15 => Ok(OpCode::PUSH5),
            0x16 => Ok(OpCode::PUSH6),
            0x17 => Ok(OpCode::PUSH7),
            0x18 => Ok(OpCode::PUSH8),
            0x19 => Ok(OpCode::PUSH9),
            0x1A => Ok(OpCode::PUSH10),
            0x1B => Ok(OpCode::PUSH11),
            0x1C => Ok(OpCode::PUSH12),
            0x1D => Ok(OpCode::PUSH13),
            0x1E => Ok(OpCode::PUSH14),
            0x1F => Ok(OpCode::PUSH15),
            0x20 => Ok(OpCode::PUSH16),
            0x21 => Ok(OpCode::NOP),
            0x22 => Ok(OpCode::JMP),
            0x23 => Ok(OpCode::JMP_L),
            0x24 => Ok(OpCode::JMPIF),
            0x25 => Ok(OpCode::JMPIF_L),
            0x26 => Ok(OpCode::JMPIFNOT),
            0x27 => Ok(OpCode::JMPIFNOT_L),
            0x28 => Ok(OpCode::JMPEQ),
            0x29 => Ok(OpCode::JMPEQ_L),
            0x2A => Ok(OpCode::JMPNE),
            0x2B => Ok(OpCode::JMPNE_L),
            0x2C => Ok(OpCode::JMPGT),
            0x2D => Ok(OpCode::JMPGT_L),
            0x2E => Ok(OpCode::JMPGE),
            0x2F => Ok(OpCode::JMPGE_L),
            0x30 => Ok(OpCode::JMPLT),
            0x31 => Ok(OpCode::JMPLT_L),
            0x32 => Ok(OpCode::JMPLE),
            0x33 => Ok(OpCode::JMPLE_L),
            0x34 => Ok(OpCode::CALL),
            0x35 => Ok(OpCode::CALL_L),
            0x36 => Ok(OpCode::CALLA),
            0x37 => Ok(OpCode::CALLT),
            0x38 => Ok(OpCode::ABORT),
            0x39 => Ok(OpCode::ASSERT),
            0x3A => Ok(OpCode::THROW),
            0x3B => Ok(OpCode::TRY),
            0x3C => Ok(OpCode::TRY_L),
            0x3D => Ok(OpCode::ENDTRY),
            0x3E => Ok(OpCode::ENDTRY_L),
            0x3F => Ok(OpCode::ENDFINALLY),
            0x40 => Ok(OpCode::RET),
            0x41 => Ok(OpCode::SYSCALL),
            0x43 => Ok(OpCode::DEPTH),
            0x45 => Ok(OpCode::DROP),
            0x46 => Ok(OpCode::NIP),
            0x48 => Ok(OpCode::XDROP),
            0x49 => Ok(OpCode::CLEAR),
            0x4A => Ok(OpCode::DUP),
            0x4B => Ok(OpCode::OVER),
            0x4D => Ok(OpCode::PICK),
            0x4E => Ok(OpCode::TUCK),
            0x50 => Ok(OpCode::SWAP),
            0x51 => Ok(OpCode::ROT),
            0x52 => Ok(OpCode::ROLL),
            0x53 => Ok(OpCode::REVERSE3),
            0x54 => Ok(OpCode::REVERSE4),
            0x55 => Ok(OpCode::REVERSEN),
            0x56 => Ok(OpCode::INITSSLOT),
            0x57 => Ok(OpCode::INITSLOT),
            0x58 => Ok(OpCode::LDSFLD0),
            0x59 => Ok(OpCode::LDSFLD1),
            0x5A => Ok(OpCode::LDSFLD2),
            0x5B => Ok(OpCode::LDSFLD3),
            0x5C => Ok(OpCode::LDSFLD4),
            0x5D => Ok(OpCode::LDSFLD5),
            0x5E => Ok(OpCode::LDSFLD),
            0x5F => Ok(OpCode::STSFLD0),
            0x60 => Ok(OpCode::STSFLD1),
            0x61 => Ok(OpCode::STSFLD2),
            0x62 => Ok(OpCode::STSFLD3),
            0x63 => Ok(OpCode::STSFLD4),
            0x64 => Ok(OpCode::STSFLD5),
            0x65 => Ok(OpCode::STSFLD),
            0x66 => Ok(OpCode::LDLOC0),
            0x67 => Ok(OpCode::LDLOC1),
            0x68 => Ok(OpCode::LDLOC2),
            0x69 => Ok(OpCode::LDLOC3),
            0x6A => Ok(OpCode::LDLOC4),
            0x6B => Ok(OpCode::LDLOC5),
            0x6C => Ok(OpCode::LDLOC),
            0x6D => Ok(OpCode::STLOC0),
            0x6E => Ok(OpCode::STLOC1),
            0x6F => Ok(OpCode::STLOC2),
            0x70 => Ok(OpCode::STLOC3),
            0x71 => Ok(OpCode::STLOC4),
            0x72 => Ok(OpCode::STLOC5),
            0x73 => Ok(OpCode::STLOC),
            0x74 => Ok(OpCode::LDARG0),
            0x75 => Ok(OpCode::LDARG1),
            0x76 => Ok(OpCode::LDARG2),
            0x77 => Ok(OpCode::LDARG3),
            0x78 => Ok(OpCode::LDARG4),
            0x79 => Ok(OpCode::LDARG5),
            0x7A => Ok(OpCode::LDARG),
            0x7B => Ok(OpCode::STARG0),
            0x7C => Ok(OpCode::STARG1),
            0x7D => Ok(OpCode::STARG2),
            0x7E => Ok(OpCode::STARG3),
            0x7F => Ok(OpCode::STARG4),
            0x80 => Ok(OpCode::STARG5),
            0x81 => Ok(OpCode::STARG),
            0x88 => Ok(OpCode::NEWBUFFER),
            0x89 => Ok(OpCode::MEMCPY),
            0x8B => Ok(OpCode::CAT),
            0x8C => Ok(OpCode::SUBSTR),
            0x8D => Ok(OpCode::LEFT),
            0x8E => Ok(OpCode::RIGHT),
            0x90 => Ok(OpCode::INVERT),
            0x91 => Ok(OpCode::AND),
            0x92 => Ok(OpCode::OR),
            0x93 => Ok(OpCode::XOR),
            0x97 => Ok(OpCode::EQUAL),
            0x98 => Ok(OpCode::NOTEQUAL),
            0x99 => Ok(OpCode::SIGN),
            0x9A => Ok(OpCode::ABS),
            0x9B => Ok(OpCode::NEGATE),
            0x9C => Ok(OpCode::INC),
            0x9D => Ok(OpCode::DEC),
            0x9E => Ok(OpCode::ADD),
            0x9F => Ok(OpCode::SUB),
            0xA0 => Ok(OpCode::MUL),
            0xA1 => Ok(OpCode::DIV),
            0xA2 => Ok(OpCode::MOD),
            0xA3 => Ok(OpCode::POW),
            0xA4 => Ok(OpCode::SQRT),
            0xA5 => Ok(OpCode::MODMUL),
            0xA6 => Ok(OpCode::MODPOW),
            0xA8 => Ok(OpCode::SHL),
            0xA9 => Ok(OpCode::SHR),
            0xAA => Ok(OpCode::NOT),
            0xAB => Ok(OpCode::BOOLAND),
            0xAC => Ok(OpCode::BOOLOR),
            0xB1 => Ok(OpCode::NZ),
            0xB3 => Ok(OpCode::NUMEQUAL),
            0xB4 => Ok(OpCode::NUMNOTEQUAL),
            0xB5 => Ok(OpCode::LT),
            0xB6 => Ok(OpCode::LE),
            0xB7 => Ok(OpCode::GT),
            0xB8 => Ok(OpCode::GE),
            0xB9 => Ok(OpCode::MIN),
            0xBA => Ok(OpCode::MAX),
            0xBB => Ok(OpCode::WITHIN),
            0xBE => Ok(OpCode::PACKMAP),
            0xBF => Ok(OpCode::PACKSTRUCT),
            0xC0 => Ok(OpCode::PACK),
            0xC1 => Ok(OpCode::UNPACK),
            0xC2 => Ok(OpCode::NEWARRAY0),
            0xC3 => Ok(OpCode::NEWARRAY),
            0xC4 => Ok(OpCode::NEWARRAY_T),
            0xC5 => Ok(OpCode::NEWSTRUCT0),
            0xC6 => Ok(OpCode::NEWSTRUCT),
            0xC8 => Ok(OpCode::NEWMAP),
            0xCA => Ok(OpCode::SIZE),
            0xCB => Ok(OpCode::HASKEY),
            0xCC => Ok(OpCode::KEYS),
            0xCD => Ok(OpCode::VALUES),
            0xCE => Ok(OpCode::PICKITEM),
            0xCF => Ok(OpCode::APPEND),
            0xD0 => Ok(OpCode::SETITEM),
            0xD1 => Ok(OpCode::REVERSEITEMS),
            0xD2 => Ok(OpCode::REMOVE),
            0xD3 => Ok(OpCode::CLEARITEMS),
            0xD4 => Ok(OpCode::POPITEM),
            0xD8 => Ok(OpCode::ISNULL),
            0xD9 => Ok(OpCode::ISTYPE),
            0xDA => Ok(OpCode::TYPE),
            0xDB => Ok(OpCode::CONVERT),
            0xE0 => Ok(OpCode::ABORTMSG),
            0xE1 => Ok(OpCode::ASSERTMSG),
            0xF0 => Ok(OpCode::SHA256),
            0xF1 => Ok(OpCode::RIPEMD160),
            0xF2 => Ok(OpCode::HASH160),
            0xF3 => Ok(OpCode::CHECKSIG),
            _ => Err(format!("Unknown opcode: 0x{:02X}", byte)),
        }
    }
}

impl OpCode {
    /// Returns the number of fixed operand bytes that follow this opcode.
    /// For variable-length opcodes (PUSHDATA1/2/4, PUSHINT*), returns the
    /// size of the length prefix only; the caller must read the actual data.
    #[must_use]
    pub fn operand_size(&self) -> usize {
        match self {
            // 1-byte offset jumps and calls
            OpCode::JMP
            | OpCode::JMPIF
            | OpCode::JMPIFNOT
            | OpCode::JMPEQ
            | OpCode::JMPNE
            | OpCode::JMPGT
            | OpCode::JMPGE
            | OpCode::JMPLT
            | OpCode::JMPLE
            | OpCode::CALL
            | OpCode::ENDTRY => 1,
            // 4-byte offset jumps and calls
            OpCode::JMP_L
            | OpCode::JMPIF_L
            | OpCode::JMPIFNOT_L
            | OpCode::JMPEQ_L
            | OpCode::JMPNE_L
            | OpCode::JMPGT_L
            | OpCode::JMPGE_L
            | OpCode::JMPLT_L
            | OpCode::JMPLE_L
            | OpCode::CALL_L
            | OpCode::ENDTRY_L
            | OpCode::SYSCALL => 4,
            // TRY has 2 one-byte offsets
            OpCode::TRY => 2,
            // TRY_L has 2 four-byte offsets
            OpCode::TRY_L => 8,
            // PUSHINT variants
            OpCode::PUSHINT8 => 1,
            OpCode::PUSHINT16 => 2,
            OpCode::PUSHINT32 => 4,
            OpCode::PUSHINT64 => 8,
            OpCode::PUSHINT128 => 16,
            OpCode::PUSHINT256 => 32,
            // PUSHDATA has variable length prefix
            OpCode::PUSHDATA1 => 1,
            OpCode::PUSHDATA2 => 2,
            OpCode::PUSHDATA4 => 4,
            // PUSHA has 4-byte address
            OpCode::PUSHA => 4,
            // CALLT has 2-byte token
            OpCode::CALLT => 2,
            // Slot init
            OpCode::INITSSLOT => 1,
            OpCode::INITSLOT => 2,
            // Indexed slot access
            OpCode::LDSFLD
            | OpCode::STSFLD
            | OpCode::LDLOC
            | OpCode::STLOC
            | OpCode::LDARG
            | OpCode::STARG => 1,
            // ISTYPE and CONVERT take 1-byte type
            OpCode::ISTYPE | OpCode::CONVERT => 1,
            // NEWARRAY_T takes 1-byte type
            OpCode::NEWARRAY_T => 1,
            // All other opcodes have no operands
            _ => 0,
        }
    }

    /// Returns the canonical name of this opcode as a static string.
    #[must_use]
    pub fn name(&self) -> &'static str {
        match self {
            OpCode::PUSHINT8 => "PUSHINT8",
            OpCode::PUSHINT16 => "PUSHINT16",
            OpCode::PUSHINT32 => "PUSHINT32",
            OpCode::PUSHINT64 => "PUSHINT64",
            OpCode::PUSHINT128 => "PUSHINT128",
            OpCode::PUSHINT256 => "PUSHINT256",
            OpCode::PUSHA => "PUSHA",
            OpCode::PUSHNULL => "PUSHNULL",
            OpCode::PUSHDATA1 => "PUSHDATA1",
            OpCode::PUSHDATA2 => "PUSHDATA2",
            OpCode::PUSHDATA4 => "PUSHDATA4",
            OpCode::PUSHM1 => "PUSHM1",
            OpCode::PUSH0 => "PUSH0",
            OpCode::PUSH1 => "PUSH1",
            OpCode::PUSH2 => "PUSH2",
            OpCode::PUSH3 => "PUSH3",
            OpCode::PUSH4 => "PUSH4",
            OpCode::PUSH5 => "PUSH5",
            OpCode::PUSH6 => "PUSH6",
            OpCode::PUSH7 => "PUSH7",
            OpCode::PUSH8 => "PUSH8",
            OpCode::PUSH9 => "PUSH9",
            OpCode::PUSH10 => "PUSH10",
            OpCode::PUSH11 => "PUSH11",
            OpCode::PUSH12 => "PUSH12",
            OpCode::PUSH13 => "PUSH13",
            OpCode::PUSH14 => "PUSH14",
            OpCode::PUSH15 => "PUSH15",
            OpCode::PUSH16 => "PUSH16",
            OpCode::NOP => "NOP",
            OpCode::JMP => "JMP",
            OpCode::JMP_L => "JMP_L",
            OpCode::JMPIF => "JMPIF",
            OpCode::JMPIF_L => "JMPIF_L",
            OpCode::JMPIFNOT => "JMPIFNOT",
            OpCode::JMPIFNOT_L => "JMPIFNOT_L",
            OpCode::JMPEQ => "JMPEQ",
            OpCode::JMPEQ_L => "JMPEQ_L",
            OpCode::JMPNE => "JMPNE",
            OpCode::JMPNE_L => "JMPNE_L",
            OpCode::JMPGT => "JMPGT",
            OpCode::JMPGT_L => "JMPGT_L",
            OpCode::JMPGE => "JMPGE",
            OpCode::JMPGE_L => "JMPGE_L",
            OpCode::JMPLT => "JMPLT",
            OpCode::JMPLT_L => "JMPLT_L",
            OpCode::JMPLE => "JMPLE",
            OpCode::JMPLE_L => "JMPLE_L",
            OpCode::CALL => "CALL",
            OpCode::CALL_L => "CALL_L",
            OpCode::CALLA => "CALLA",
            OpCode::CALLT => "CALLT",
            OpCode::ABORT => "ABORT",
            OpCode::ASSERT => "ASSERT",
            OpCode::THROW => "THROW",
            OpCode::TRY => "TRY",
            OpCode::TRY_L => "TRY_L",
            OpCode::ENDTRY => "ENDTRY",
            OpCode::ENDTRY_L => "ENDTRY_L",
            OpCode::ENDFINALLY => "ENDFINALLY",
            OpCode::RET => "RET",
            OpCode::SYSCALL => "SYSCALL",
            OpCode::DEPTH => "DEPTH",
            OpCode::DROP => "DROP",
            OpCode::NIP => "NIP",
            OpCode::XDROP => "XDROP",
            OpCode::CLEAR => "CLEAR",
            OpCode::DUP => "DUP",
            OpCode::OVER => "OVER",
            OpCode::PICK => "PICK",
            OpCode::TUCK => "TUCK",
            OpCode::SWAP => "SWAP",
            OpCode::ROT => "ROT",
            OpCode::ROLL => "ROLL",
            OpCode::REVERSE3 => "REVERSE3",
            OpCode::REVERSE4 => "REVERSE4",
            OpCode::REVERSEN => "REVERSEN",
            OpCode::INITSSLOT => "INITSSLOT",
            OpCode::INITSLOT => "INITSLOT",
            OpCode::LDSFLD0 => "LDSFLD0",
            OpCode::LDSFLD1 => "LDSFLD1",
            OpCode::LDSFLD2 => "LDSFLD2",
            OpCode::LDSFLD3 => "LDSFLD3",
            OpCode::LDSFLD4 => "LDSFLD4",
            OpCode::LDSFLD5 => "LDSFLD5",
            OpCode::LDSFLD => "LDSFLD",
            OpCode::STSFLD0 => "STSFLD0",
            OpCode::STSFLD1 => "STSFLD1",
            OpCode::STSFLD2 => "STSFLD2",
            OpCode::STSFLD3 => "STSFLD3",
            OpCode::STSFLD4 => "STSFLD4",
            OpCode::STSFLD5 => "STSFLD5",
            OpCode::STSFLD => "STSFLD",
            OpCode::LDLOC0 => "LDLOC0",
            OpCode::LDLOC1 => "LDLOC1",
            OpCode::LDLOC2 => "LDLOC2",
            OpCode::LDLOC3 => "LDLOC3",
            OpCode::LDLOC4 => "LDLOC4",
            OpCode::LDLOC5 => "LDLOC5",
            OpCode::LDLOC => "LDLOC",
            OpCode::STLOC0 => "STLOC0",
            OpCode::STLOC1 => "STLOC1",
            OpCode::STLOC2 => "STLOC2",
            OpCode::STLOC3 => "STLOC3",
            OpCode::STLOC4 => "STLOC4",
            OpCode::STLOC5 => "STLOC5",
            OpCode::STLOC => "STLOC",
            OpCode::LDARG0 => "LDARG0",
            OpCode::LDARG1 => "LDARG1",
            OpCode::LDARG2 => "LDARG2",
            OpCode::LDARG3 => "LDARG3",
            OpCode::LDARG4 => "LDARG4",
            OpCode::LDARG5 => "LDARG5",
            OpCode::LDARG => "LDARG",
            OpCode::STARG0 => "STARG0",
            OpCode::STARG1 => "STARG1",
            OpCode::STARG2 => "STARG2",
            OpCode::STARG3 => "STARG3",
            OpCode::STARG4 => "STARG4",
            OpCode::STARG5 => "STARG5",
            OpCode::STARG => "STARG",
            OpCode::NEWBUFFER => "NEWBUFFER",
            OpCode::MEMCPY => "MEMCPY",
            OpCode::CAT => "CAT",
            OpCode::SUBSTR => "SUBSTR",
            OpCode::LEFT => "LEFT",
            OpCode::RIGHT => "RIGHT",
            OpCode::INVERT => "INVERT",
            OpCode::AND => "AND",
            OpCode::OR => "OR",
            OpCode::XOR => "XOR",
            OpCode::EQUAL => "EQUAL",
            OpCode::NOTEQUAL => "NOTEQUAL",
            OpCode::SIGN => "SIGN",
            OpCode::ABS => "ABS",
            OpCode::NEGATE => "NEGATE",
            OpCode::INC => "INC",
            OpCode::DEC => "DEC",
            OpCode::ADD => "ADD",
            OpCode::SUB => "SUB",
            OpCode::MUL => "MUL",
            OpCode::DIV => "DIV",
            OpCode::MOD => "MOD",
            OpCode::POW => "POW",
            OpCode::SQRT => "SQRT",
            OpCode::MODMUL => "MODMUL",
            OpCode::MODPOW => "MODPOW",
            OpCode::SHL => "SHL",
            OpCode::SHR => "SHR",
            OpCode::NOT => "NOT",
            OpCode::BOOLAND => "BOOLAND",
            OpCode::BOOLOR => "BOOLOR",
            OpCode::NZ => "NZ",
            OpCode::NUMEQUAL => "NUMEQUAL",
            OpCode::NUMNOTEQUAL => "NUMNOTEQUAL",
            OpCode::LT => "LT",
            OpCode::LE => "LE",
            OpCode::GT => "GT",
            OpCode::GE => "GE",
            OpCode::MIN => "MIN",
            OpCode::MAX => "MAX",
            OpCode::WITHIN => "WITHIN",
            OpCode::PACKMAP => "PACKMAP",
            OpCode::PACKSTRUCT => "PACKSTRUCT",
            OpCode::PACK => "PACK",
            OpCode::UNPACK => "UNPACK",
            OpCode::NEWARRAY0 => "NEWARRAY0",
            OpCode::NEWARRAY => "NEWARRAY",
            OpCode::NEWARRAY_T => "NEWARRAY_T",
            OpCode::NEWSTRUCT0 => "NEWSTRUCT0",
            OpCode::NEWSTRUCT => "NEWSTRUCT",
            OpCode::NEWMAP => "NEWMAP",
            OpCode::SIZE => "SIZE",
            OpCode::HASKEY => "HASKEY",
            OpCode::KEYS => "KEYS",
            OpCode::VALUES => "VALUES",
            OpCode::PICKITEM => "PICKITEM",
            OpCode::APPEND => "APPEND",
            OpCode::SETITEM => "SETITEM",
            OpCode::REVERSEITEMS => "REVERSEITEMS",
            OpCode::REMOVE => "REMOVE",
            OpCode::CLEARITEMS => "CLEARITEMS",
            OpCode::POPITEM => "POPITEM",
            OpCode::ISNULL => "ISNULL",
            OpCode::ISTYPE => "ISTYPE",
            OpCode::TYPE => "TYPE",
            OpCode::CONVERT => "CONVERT",
            OpCode::ABORTMSG => "ABORTMSG",
            OpCode::ASSERTMSG => "ASSERTMSG",
            OpCode::SHA256 => "SHA256",
            OpCode::RIPEMD160 => "RIPEMD160",
            OpCode::HASH160 => "HASH160",
            OpCode::CHECKSIG => "CHECKSIG",
        }
    }
}

impl std::fmt::Display for OpCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}
