//! Neo zkVM Prover with SP1 Integration
//!
//! Production-grade prover using SP1 zkVM for generating zero-knowledge proofs.
//!
//! ## Quick Start
//!
//! ```rust
//! use neo_zkvm_prover::{NeoProver, ProverConfig, ProofMode};
//! use neo_vm_guest::ProofInput;
//!
//! // Use mock mode for local/debug development.
//! let prover = NeoProver::new(ProverConfig {
//!     proof_mode: ProofMode::Mock,
//!     ..Default::default()
//! });
//!
//! // Define input
//! let input = ProofInput {
//!     script: vec![0x12, 0x13, 0x9E, 0x40], // 2 + 3
//!     arguments: vec![],
//!     gas_limit: 1_000_000,
//! };
//!
//! // Generate proof
//! let proof = prover.prove(input);
//! ```

use bincode::Options;
use neo_vm_guest::{execute, ProofInput, ProofOutput};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use sp1_sdk::{ProverClient, SP1ProofMode, SP1PublicValues, SP1Stdin};

/// SP1 ELF binary - embedded at compile time
/// This is the compiled guest program that runs inside SP1 zkVM
///
/// Note: If SP1 toolchain is not installed, this will be a dummy value
/// and proof generation will fall back to mock mode.
pub const NEO_ZKVM_ELF: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/elf/riscv32im-succinct-zkvm-elf"));

const BINCODE_LIMIT: u64 = 10 * 1024 * 1024; // 10MB limit

// NeoProof serialization format version.
// Increment this when NeoProof structure or semantics change incompatibly.
pub const PROOF_FORMAT_VERSION: u16 = 1;

type DynError = Box<dyn std::error::Error>;
type Sp1ProofArtifacts = (Vec<u8>, [u8; 32], PublicInputs);

fn bincode_options() -> impl Options {
    bincode::DefaultOptions::new()
        .with_limit(BINCODE_LIMIT)
        .with_fixint_encoding()
}

/// Proof generated by the prover
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct NeoProof {
    /// Execution output
    pub output: ProofOutput,
    /// SP1 proof bytes
    pub proof_bytes: Vec<u8>,
    /// Public inputs for verification
    pub public_inputs: PublicInputs,
    /// Verification key hash
    pub vkey_hash: [u8; 32],
    /// Proof mode used
    pub proof_mode: ProofMode,
    /// NeoProof serialization format version.
    pub proof_format_version: u16,
}

/// Public inputs for verification
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct PublicInputs {
    /// Hash of the executed script
    pub script_hash: [u8; 32],
    /// Hash of input arguments
    pub input_hash: [u8; 32],
    /// Hash of execution output
    pub output_hash: [u8; 32],
    /// Gas consumed during execution
    pub gas_consumed: u64,
    /// Whether execution succeeded
    pub execution_success: bool,
}

/// Prover configuration
#[derive(Clone, Debug)]
pub struct ProverConfig {
    /// Maximum cycles for SP1 execution
    pub max_cycles: u64,
    /// Proof mode (determines proof type and verification cost)
    pub proof_mode: ProofMode,
}

/// Proof mode - determines the type of proof generated.
///
/// Each mode trades off between proving speed, proof size, and verification cost:
///
/// | Mode      | Proving Speed | Proof Size | Verification Cost | Use Case                        |
/// |-----------|---------------|------------|-------------------|---------------------------------|
/// | Execute   | Instant       | None       | N/A (no proof)    | Local debugging, dry-runs       |
/// | Mock      | Fast          | Small      | Cheap (hash only) | Unit tests, CI pipelines        |
/// | Sp1       | Slow          | Large      | Medium            | Off-chain verification          |
/// | Plonk     | Slower        | Medium     | Lower             | On-chain with moderate gas cost |
/// | Groth16   | Slowest       | Smallest   | Lowest            | Ethereum L1 verification        |
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofMode {
    /// Execute only, no proof generation (fastest).
    /// Useful for local debugging and dry-runs where no cryptographic guarantee is needed.
    Execute,
    /// Mock proof for testing (fast, not cryptographically secure).
    /// Produces a commitment-based proof suitable for unit tests and CI, but not
    /// verifiable by a third party.
    Mock,
    /// SP1 compressed proof (fast verification, larger proof).
    /// Good default for off-chain verification where proof size is not critical.
    Sp1,
    /// SP1 PLONK proof (medium verification cost, smaller proof).
    /// Suitable for on-chain verification with moderate gas budgets.
    Plonk,
    /// SP1 Groth16 proof (slowest to generate, smallest proof, cheapest to verify).
    /// Best choice for Ethereum L1 verification where gas cost must be minimized.
    Groth16,
}

impl Default for ProverConfig {
    fn default() -> Self {
        Self {
            max_cycles: 10_000_000,
            proof_mode: ProofMode::Sp1,
        }
    }
}

/// Neo zkVM Prover
pub struct NeoProver {
    config: ProverConfig,
}

impl NeoProver {
    /// Check if the SP1 ELF is available and valid
    pub fn is_elf_available() -> bool {
        !NEO_ZKVM_ELF.is_empty() && NEO_ZKVM_ELF.len() > 100 &&
        // Check it's not our dummy marker
        !NEO_ZKVM_ELF.starts_with(b"DUMMY")
    }

    fn sp1_unavailable_reason() -> &'static str {
        if NEO_ZKVM_ELF.starts_with(b"DUMMY_ELF_NO_PROGRAM_SOURCE") {
            "SP1 prover was built without neo-zkvm-program source"
        } else if NEO_ZKVM_ELF.starts_with(b"DUMMY_ELF_NOT_FOR_PRODUCTION") {
            "SP1 toolchain is not installed"
        } else if NEO_ZKVM_ELF.starts_with(b"DUMMY_ELF_FOR_CLIPPY") {
            "SP1 ELF build was skipped for clippy/analysis"
        } else {
            "SP1 ELF is unavailable"
        }
    }

    /// Create a new prover with the given configuration
    ///
    /// If SP1 is not available, it will fall back to mock mode.
    pub fn new(config: ProverConfig) -> Self {
        Self { config }
    }

    /// Maximum allowed script size (1 MB).
    const MAX_SCRIPT_SIZE: usize = 1024 * 1024;

    /// Generate a proof for the given input.
    ///
    /// The proof mode in the config determines what type of proof is generated.
    /// If SP1 is not available, automatically falls back to mock mode.
    ///
    /// Returns a faulted `NeoProof` if the input script exceeds 1 MB.
    pub fn prove(&self, input: ProofInput) -> NeoProof {
        // Validate input script size before doing any work
        if input.script.len() > Self::MAX_SCRIPT_SIZE {
            return NeoProof {
                output: ProofOutput {
                    state: 1,
                    result: Some(neo_vm_core::StackItem::Boolean(false)),
                    gas_consumed: 0,
                    error: Some(format!(
                        "Script size {} bytes exceeds maximum allowed size of {} bytes",
                        input.script.len(),
                        Self::MAX_SCRIPT_SIZE,
                    )),
                },
                proof_bytes: vec![],
                public_inputs: PublicInputs {
                    script_hash: [0u8; 32],
                    input_hash: [0u8; 32],
                    output_hash: [0u8; 32],
                    gas_consumed: 0,
                    execution_success: false,
                },
                vkey_hash: [0u8; 32],
                proof_mode: self.config.proof_mode,
                proof_format_version: PROOF_FORMAT_VERSION,
            };
        }

        // Compute hashes for public inputs
        let script_hash = Self::hash_data(&input.script);
        let input_hash = Self::hash_proof_input(&input);

        // Execute to get output (used for all modes)
        let output = execute(input.clone());
        let output_bytes = bincode_options().serialize(&output).unwrap_or_default();
        let output_hash = Self::hash_data(&output_bytes);

        let mut public_inputs = PublicInputs {
            script_hash,
            input_hash,
            output_hash,
            gas_consumed: output.gas_consumed,
            execution_success: output.state == 0,
        };

        // Check if SP1 is available
        let sp1_available = Self::is_elf_available();

        // Generate proof based on mode (fallback to mock if SP1 not available)
        let (proof_bytes, vkey_hash, actual_mode, sp1_public_inputs) = match self.config.proof_mode
        {
            ProofMode::Execute => (vec![], [0u8; 32], ProofMode::Execute, None),
            ProofMode::Mock => (
                self.generate_mock_proof(&public_inputs),
                [0u8; 32],
                ProofMode::Mock,
                None,
            ),
            ProofMode::Sp1 if sp1_available => {
                match self.generate_sp1_proof(&input, SP1ProofMode::Compressed) {
                    Ok((bytes, hash, inputs)) => (bytes, hash, ProofMode::Sp1, Some(inputs)),
                    Err(err) => {
                        eprintln!(
                            "Warning: SP1 proof generation failed ({err}), falling back to mock"
                        );
                        (
                            self.generate_mock_proof(&public_inputs),
                            [0u8; 32],
                            ProofMode::Mock,
                            None,
                        )
                    }
                }
            }
            ProofMode::Plonk if sp1_available => {
                match self.generate_sp1_proof(&input, SP1ProofMode::Plonk) {
                    Ok((bytes, hash, inputs)) => (bytes, hash, ProofMode::Plonk, Some(inputs)),
                    Err(err) => {
                        eprintln!(
                            "Warning: PLONK proof generation failed ({err}), falling back to mock"
                        );
                        (
                            self.generate_mock_proof(&public_inputs),
                            [0u8; 32],
                            ProofMode::Mock,
                            None,
                        )
                    }
                }
            }
            ProofMode::Groth16 if sp1_available => {
                match self.generate_sp1_proof(&input, SP1ProofMode::Groth16) {
                    Ok((bytes, hash, inputs)) => (bytes, hash, ProofMode::Groth16, Some(inputs)),
                    Err(err) => {
                        eprintln!("Warning: Groth16 proof generation failed ({err}), falling back to mock");
                        (
                            self.generate_mock_proof(&public_inputs),
                            [0u8; 32],
                            ProofMode::Mock,
                            None,
                        )
                    }
                }
            }
            // Fallback to mock for SP1 modes when ELF not available
            _ => {
                eprintln!(
                    "Warning: {}. Falling back to mock proof. For real SP1 proofs, build from source or reinstall with NEO_ZKVM_PROGRAM_DIR=/path/to/neo-zkvm-program.",
                    Self::sp1_unavailable_reason()
                );
                (
                    self.generate_mock_proof(&public_inputs),
                    [0u8; 32],
                    ProofMode::Mock,
                    None,
                )
            }
        };

        if let Some(inputs) = sp1_public_inputs {
            if !public_inputs_equal(&inputs, &public_inputs) {
                eprintln!(
                    "Warning: SP1 public inputs differ from host execution summary; falling back to mock proof"
                );
                return NeoProof {
                    output,
                    proof_bytes: self.generate_mock_proof(&public_inputs),
                    public_inputs,
                    vkey_hash: [0u8; 32],
                    proof_mode: ProofMode::Mock,
                    proof_format_version: PROOF_FORMAT_VERSION,
                };
            }

            public_inputs = inputs;
        }

        NeoProof {
            output,
            proof_bytes,
            public_inputs,
            vkey_hash,
            proof_mode: actual_mode,
            proof_format_version: PROOF_FORMAT_VERSION,
        }
    }

    /// Verify a proof
    ///
    /// Returns true if the proof is valid, false otherwise.
    pub fn verify(&self, proof: &NeoProof) -> bool {
        if proof.proof_format_version != PROOF_FORMAT_VERSION {
            return false;
        }

        if !Self::output_matches_public_inputs(proof) {
            return false;
        }

        match proof.proof_mode {
            ProofMode::Execute => proof.output.state == 0,
            ProofMode::Mock => proof.output.state == 0 && self.verify_mock_proof(proof),
            ProofMode::Sp1 | ProofMode::Plonk | ProofMode::Groth16 => {
                proof.output.state == 0 && self.verify_sp1_proof(proof).unwrap_or(false)
            }
        }
    }

    fn hash_data(data: &[u8]) -> [u8; 32] {
        let mut hasher = Sha256::new();
        hasher.update(data);
        hasher.finalize().into()
    }

    fn hash_proof_input(input: &ProofInput) -> [u8; 32] {
        let bytes = bincode_options().serialize(input).unwrap_or_default();
        Self::hash_data(&bytes)
    }

    fn hash_proof_output(output: &ProofOutput) -> [u8; 32] {
        let output_bytes = bincode_options().serialize(output).unwrap_or_default();
        Self::hash_data(&output_bytes)
    }

    fn output_matches_public_inputs(proof: &NeoProof) -> bool {
        proof.public_inputs.output_hash == Self::hash_proof_output(&proof.output)
            && proof.public_inputs.gas_consumed == proof.output.gas_consumed
            && proof.public_inputs.execution_success == (proof.output.state == 0)
    }

    fn generate_mock_proof(&self, inputs: &PublicInputs) -> Vec<u8> {
        let mock = MockProof {
            public_inputs: inputs.clone(),
            commitment: Self::compute_commitment(inputs),
            timestamp: std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs(),
        };
        bincode_options().serialize(&mock).unwrap_or_default()
    }

    fn verify_mock_proof(&self, proof: &NeoProof) -> bool {
        match bincode_options().deserialize::<MockProof>(&proof.proof_bytes) {
            Ok(mock) => {
                let expected = Self::compute_commitment(&proof.public_inputs);
                mock.commitment == expected
                    && mock.public_inputs.script_hash == proof.public_inputs.script_hash
            }
            Err(_) => false,
        }
    }

    fn generate_sp1_proof(
        &self,
        input: &ProofInput,
        mode: sp1_sdk::SP1ProofMode,
    ) -> Result<Sp1ProofArtifacts, DynError> {
        if cfg!(debug_assertions) {
            return Err("SP1 proving requires a release build (--release)".into());
        }

        // Only run if ELF is available
        if !Self::is_elf_available() {
            return Err(Self::sp1_unavailable_reason().into());
        }

        let prover = ProverClient::from_env();
        let (pk, vk) = prover.setup(NEO_ZKVM_ELF);

        let stdin = self.prepare_stdin(input);

        // Build and run the proof based on mode
        let proof = match mode {
            sp1_sdk::SP1ProofMode::Core => prover.prove(&pk, &stdin).core().run(),
            sp1_sdk::SP1ProofMode::Compressed => prover.prove(&pk, &stdin).compressed().run(),
            sp1_sdk::SP1ProofMode::Plonk => prover.prove(&pk, &stdin).plonk().run(),
            sp1_sdk::SP1ProofMode::Groth16 => prover.prove(&pk, &stdin).groth16().run(),
        }?;

        // Verify immediately to catch any issues
        prover.verify(&proof, &vk)?;

        let public_inputs = decode_public_inputs(&proof.public_values)?;
        let proof_bytes = bincode_options().serialize(&proof)?;
        let vkey_hash = Self::hash_data(&bincode_options().serialize(&vk)?);

        Ok((proof_bytes, vkey_hash, public_inputs))
    }

    fn verify_sp1_proof(&self, proof: &NeoProof) -> Result<bool, DynError> {
        if !Self::is_elf_available() {
            return Ok(false);
        }

        let prover = ProverClient::from_env();
        let (_, vk) = prover.setup(NEO_ZKVM_ELF);

        let sp1_proof: sp1_sdk::SP1ProofWithPublicValues =
            bincode_options().deserialize(&proof.proof_bytes)?;
        let public_inputs = decode_public_inputs(&sp1_proof.public_values)?;
        if !public_inputs_equal(&public_inputs, &proof.public_inputs) {
            return Ok(false);
        }

        match prover.verify(&sp1_proof, &vk) {
            Ok(_) => Ok(true),
            Err(_) => Ok(false),
        }
    }

    fn prepare_stdin(&self, input: &ProofInput) -> SP1Stdin {
        let mut stdin = SP1Stdin::new();

        stdin.write(input);
        stdin
    }

    fn compute_commitment(inputs: &PublicInputs) -> [u8; 32] {
        let mut hasher = Sha256::new();
        hasher.update(inputs.script_hash);
        hasher.update(inputs.input_hash);
        hasher.update(inputs.output_hash);
        hasher.update(inputs.gas_consumed.to_le_bytes());
        hasher.update([inputs.execution_success as u8]);
        hasher.finalize().into()
    }
}

fn decode_public_inputs(values: &SP1PublicValues) -> Result<PublicInputs, DynError> {
    Ok(bincode_options().deserialize(values.as_slice())?)
}

fn public_inputs_equal(a: &PublicInputs, b: &PublicInputs) -> bool {
    a.script_hash == b.script_hash
        && a.input_hash == b.input_hash
        && a.output_hash == b.output_hash
        && a.gas_consumed == b.gas_consumed
        && a.execution_success == b.execution_success
}

/// Mock proof structure for testing
#[derive(Serialize, Deserialize)]
pub struct MockProof {
    pub public_inputs: PublicInputs,
    pub commitment: [u8; 32],
    pub timestamp: u64,
}

#[cfg(test)]
mod tests {
    use super::*;
    use neo_vm_core::StackItem;

    #[test]
    fn test_mock_proof() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Mock,
            ..Default::default()
        });

        let input = ProofInput {
            script: vec![0x12, 0x13, 0x9E, 0x40],
            arguments: vec![],
            gas_limit: 1_000_000,
        };

        let proof = prover.prove(input);
        assert!(proof.proof_mode == ProofMode::Mock);
        assert!(prover.verify(&proof));
    }

    #[test]
    fn test_execute_only() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Execute,
            ..Default::default()
        });

        let input = ProofInput {
            script: vec![0x12, 0x13, 0x9E, 0x40],
            arguments: vec![],
            gas_limit: 1_000_000,
        };

        let proof = prover.prove(input);
        assert!(proof.proof_mode == ProofMode::Execute);
        assert!(prover.verify(&proof));
    }

    #[test]
    fn test_input_hash_matches_serialized_proof_input() {
        let input = ProofInput {
            script: vec![0x12, 0x13, 0x9E, 0x40],
            arguments: vec![StackItem::Integer(7)],
            gas_limit: 123,
        };

        let bytes = bincode_options().serialize(&input).expect("serialize");
        let hash = NeoProver::hash_data(&bytes);

        assert_eq!(hash, NeoProver::hash_proof_input(&input));
    }

    #[test]
    fn test_input_hash_distinguishes_complex_argument_variants() {
        let null_input = ProofInput {
            script: vec![0x40],
            arguments: vec![StackItem::Null],
            gas_limit: 1_000_000,
        };
        let array_input = ProofInput {
            script: vec![0x40],
            arguments: vec![StackItem::Array(vec![StackItem::Integer(42)])],
            gas_limit: 1_000_000,
        };

        assert_ne!(
            NeoProver::hash_proof_input(&null_input),
            NeoProver::hash_proof_input(&array_input)
        );
    }

    #[test]
    fn test_mock_proof_tamper_detection() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Mock,
            ..Default::default()
        });
        let input = ProofInput {
            script: vec![0x12, 0x13, 0x9E, 0x40],
            arguments: vec![],
            gas_limit: 1_000_000,
        };
        let mut proof = prover.prove(input);
        proof.public_inputs.script_hash[0] ^= 0xFF;
        assert!(!prover.verify(&proof));
    }

    #[test]
    fn test_proof_output_contains_result() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Execute,
            ..Default::default()
        });
        let input = ProofInput {
            script: vec![0x12, 0x13, 0x9E, 0x40],
            arguments: vec![],
            gas_limit: 1_000_000,
        };
        let proof = prover.prove(input);
        assert_eq!(proof.output.state, 0);
        assert!(proof.output.gas_consumed > 0);
    }

    #[test]
    fn test_output_tampering_is_detected() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Mock,
            ..Default::default()
        });
        let input = ProofInput {
            script: vec![0x12, 0x13, 0x9E, 0x40],
            arguments: vec![],
            gas_limit: 1_000_000,
        };
        let mut proof = prover.prove(input);
        proof.output.result = Some(StackItem::Integer(999));
        assert!(!prover.verify(&proof));
    }

    #[test]
    fn test_faulting_script_produces_failed_proof() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Mock,
            ..Default::default()
        });
        let input = ProofInput {
            script: vec![0x15, 0x10, 0xA1, 0x40], // div by zero
            arguments: vec![],
            gas_limit: 1_000_000,
        };
        let proof = prover.prove(input);
        assert_ne!(proof.output.state, 0);
    }

    #[test]
    fn test_verify_execute_faulted_proof_rejected() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Execute,
            ..Default::default()
        });

        let input = ProofInput {
            script: vec![0x15, 0x10, 0xA1, 0x40], // div by zero
            arguments: vec![],
            gas_limit: 1_000_000,
        };

        let proof = prover.prove(input);
        assert_ne!(proof.output.state, 0);
        assert!(!prover.verify(&proof));
    }

    #[test]
    fn test_verify_mock_faulted_proof_rejected() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Mock,
            ..Default::default()
        });

        let input = ProofInput {
            script: vec![0x15, 0x10, 0xA1, 0x40], // div by zero
            arguments: vec![],
            gas_limit: 1_000_000,
        };

        let proof = prover.prove(input);
        assert_ne!(proof.output.state, 0);
        assert!(!prover.verify(&proof));
    }

    #[test]
    fn test_verify_rejects_unknown_proof_format_version() {
        let prover = NeoProver::new(ProverConfig {
            proof_mode: ProofMode::Mock,
            ..Default::default()
        });

        let input = ProofInput {
            script: vec![0x12, 0x13, 0x9E, 0x40],
            arguments: vec![],
            gas_limit: 1_000_000,
        };

        let mut proof = prover.prove(input);
        proof.proof_format_version = proof.proof_format_version.saturating_add(1);

        assert!(!prover.verify(&proof));
    }
}
