//! Neo zkVM Prover

use neo_vm_guest::{ProofInput, ProofOutput, execute};
use serde::{Deserialize, Serialize};

/// Proof generated by the prover
#[derive(Serialize, Deserialize)]
pub struct NeoProof {
    pub output: ProofOutput,
    pub proof_bytes: Vec<u8>,
}

/// Prover configuration
pub struct ProverConfig {
    pub max_cycles: u64,
}

impl Default for ProverConfig {
    fn default() -> Self {
        Self { max_cycles: 1_000_000 }
    }
}

/// Neo zkVM Prover
pub struct NeoProver {
    config: ProverConfig,
}

impl NeoProver {
    pub fn new(config: ProverConfig) -> Self {
        Self { config }
    }

    /// Generate proof for script execution
    pub fn prove(&self, input: ProofInput) -> NeoProof {
        let output = execute(input);
        NeoProof {
            output,
            proof_bytes: vec![], // Placeholder
        }
    }
}
