//! Shared VM types, serialization helpers, and proof utilities for Neo zkVM.

use bincode::Options;
use neo_vm_core::{NeoVM, StackItem, VMState};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Bincode size limit (10 MB).
const BINCODE_LIMIT: u64 = 10 * 1024 * 1024;

/// NeoProof serialization format version.
/// Increment when NeoProof structure or semantics change incompatibly.
pub const PROOF_FORMAT_VERSION: u16 = 1;

const fn default_proof_format_version() -> u16 {
    PROOF_FORMAT_VERSION
}

/// Configured bincode options shared by prover and verifier.
#[must_use]
pub fn bincode_options() -> impl Options {
    bincode::DefaultOptions::new()
        .with_limit(BINCODE_LIMIT)
        .with_fixint_encoding()
}

/// Input for zkVM proving.
#[derive(Serialize, Deserialize, Clone)]
pub struct ProofInput {
    /// Raw bytecode to execute.
    pub script: Vec<u8>,
    /// Arguments passed to the script.
    pub arguments: Vec<StackItem>,
    /// Maximum gas units allowed for execution.
    pub gas_limit: u64,
}

/// Output from zkVM execution.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ProofOutput {
    /// VM exit state: 0 = halt (success), non-zero = fault.
    pub state: u8,
    /// Top-of-stack value at halt, if any.
    pub result: Option<StackItem>,
    /// Total gas consumed during execution.
    pub gas_consumed: u64,
    /// Human-readable error message on fault.
    pub error: Option<String>,
}

/// Proof mode - determines the type of proof generated.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofMode {
    /// Execute only, no proof generation.
    Execute,
    /// Mock proof for testing (not cryptographically secure).
    Mock,
    /// SP1 compressed proof.
    Sp1,
    /// SP1 PLONK proof.
    Plonk,
    /// SP1 Groth16 proof.
    Groth16,
}

/// Public inputs committed in a proof, used for verification.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct PublicInputs {
    /// SHA-256 hash of the raw script bytecode.
    pub script_hash: [u8; 32],
    /// SHA-256 hash of the serialized [`ProofInput`].
    pub input_hash: [u8; 32],
    /// SHA-256 hash of the serialized [`ProofOutput`].
    pub output_hash: [u8; 32],
    /// Total gas consumed during execution.
    pub gas_consumed: u64,
    /// Whether execution completed without fault.
    pub execution_success: bool,
}

/// Proof generated by the prover.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct NeoProof {
    /// Execution output (result, gas, error).
    pub output: ProofOutput,
    /// Serialized cryptographic proof bytes (empty for Execute mode).
    pub proof_bytes: Vec<u8>,
    /// Public inputs committed in the proof.
    pub public_inputs: PublicInputs,
    /// SHA-256 hash of the SP1 verification key (zero for mock/execute).
    pub vkey_hash: [u8; 32],
    /// The proof mode that was actually used.
    pub proof_mode: ProofMode,
    /// Serialization format version for forward compatibility.
    #[serde(default = "default_proof_format_version")]
    pub proof_format_version: u16,
}

/// Mock proof structure for testing.
#[derive(Serialize, Deserialize)]
pub struct MockProof {
    /// Public inputs used to compute the commitment.
    pub public_inputs: PublicInputs,
    /// HMAC-like commitment over the public inputs.
    pub commitment: [u8; 32],
    /// Unix timestamp when the mock proof was created.
    pub timestamp: u64,
}

// ============================================================================
// Shared utility functions
// ============================================================================

/// SHA-256 hash of arbitrary data.
#[must_use]
pub fn hash_data(data: &[u8]) -> [u8; 32] {
    Sha256::digest(data).into()
}

/// SHA-256 hash of a serialized `ProofOutput`.
pub fn try_hash_proof_output(output: &ProofOutput) -> Result<[u8; 32], bincode::Error> {
    let bytes = bincode_options().serialize(output)?;
    Ok(hash_data(&bytes))
}

/// SHA-256 hash of a serialized `ProofOutput`.
///
/// This panics if serialization fails; prefer `try_hash_proof_output` in fallible paths.
#[must_use]
pub fn hash_proof_output(output: &ProofOutput) -> [u8; 32] {
    try_hash_proof_output(output)
        .expect("failed to serialize ProofOutput for hashing; use try_hash_proof_output")
}

/// Compute commitment over all public input fields.
#[must_use]
pub fn compute_commitment(inputs: &PublicInputs) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(inputs.script_hash);
    hasher.update(inputs.input_hash);
    hasher.update(inputs.output_hash);
    hasher.update(inputs.gas_consumed.to_le_bytes());
    hasher.update([inputs.execution_success as u8]);
    hasher.finalize().into()
}

/// Check whether two `PublicInputs` are equal.
#[must_use]
pub fn public_inputs_equal(a: &PublicInputs, b: &PublicInputs) -> bool {
    a.script_hash == b.script_hash
        && a.input_hash == b.input_hash
        && a.output_hash == b.output_hash
        && a.gas_consumed == b.gas_consumed
        && a.execution_success == b.execution_success
}

/// Check whether a proof's output is consistent with its public inputs.
#[must_use]
pub fn output_matches_public_inputs(proof: &NeoProof) -> bool {
    let output_hash = match try_hash_proof_output(&proof.output) {
        Ok(hash) => hash,
        Err(_) => return false,
    };

    proof.public_inputs.output_hash == output_hash
        && proof.public_inputs.gas_consumed == proof.output.gas_consumed
        && proof.public_inputs.execution_success == (proof.output.state == 0)
}

#[derive(Deserialize)]
struct LegacyNeoProof {
    output: ProofOutput,
    proof_bytes: Vec<u8>,
    public_inputs: PublicInputs,
    vkey_hash: [u8; 32],
    proof_mode: ProofMode,
}

/// Deserialize a `NeoProof`, with compatibility fallback for legacy proofs that
/// predate `proof_format_version`.
pub fn deserialize_neoproof(bytes: &[u8]) -> Result<NeoProof, bincode::Error> {
    match bincode_options().deserialize::<NeoProof>(bytes) {
        Ok(proof) => Ok(proof),
        Err(primary_err) => match bincode_options().deserialize::<LegacyNeoProof>(bytes) {
            Ok(legacy) => Ok(NeoProof {
                output: legacy.output,
                proof_bytes: legacy.proof_bytes,
                public_inputs: legacy.public_inputs,
                vkey_hash: legacy.vkey_hash,
                proof_mode: legacy.proof_mode,
                proof_format_version: 1,
            }),
            Err(_) => Err(primary_err),
        },
    }
}

// ============================================================================
// Guest execution
// ============================================================================

/// Execute Neo VM and return proof output
#[must_use]
pub fn execute(input: ProofInput) -> ProofOutput {
    let mut vm = NeoVM::new(input.gas_limit);
    if let Err(e) = vm.load_script(input.script) {
        return ProofOutput {
            state: 1,
            gas_consumed: vm.gas_consumed,
            result: Some(StackItem::Boolean(false)),
            error: Some(e.to_string()),
        };
    }

    // Push arguments with VM's configured stack depth limit
    for arg in input.arguments {
        if vm.eval_stack.len() >= vm.max_stack_depth {
            return ProofOutput {
                state: 1,
                gas_consumed: vm.gas_consumed,
                result: Some(StackItem::Boolean(false)),
                error: Some(format!(
                    "Stack overflow: depth {} exceeds limit {}",
                    vm.eval_stack.len(),
                    vm.max_stack_depth
                )),
            };
        }
        vm.eval_stack.push(arg);
    }

    // Execute until halt or fault
    let mut runtime_error: Option<String> = None;
    while !matches!(vm.state, VMState::Halt | VMState::Fault) {
        if let Err(err) = vm.execute_next() {
            runtime_error = Some(err.to_string());
            vm.state = VMState::Fault;
            break;
        }
    }

    let state = match vm.state {
        VMState::Halt => 0,
        VMState::Fault => 1,
        _ => 2,
    };

    ProofOutput {
        state,
        result: vm.eval_stack.pop(),
        gas_consumed: vm.gas_consumed,
        error: if state == 1 {
            runtime_error.or_else(|| Some("Execution fault".to_string()))
        } else {
            None
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::Serialize;

    #[test]
    fn test_output_matches_public_inputs_roundtrip() {
        let output = ProofOutput {
            state: 0,
            result: Some(StackItem::Integer(5)),
            gas_consumed: 42,
            error: None,
        };
        let proof = NeoProof {
            output: output.clone(),
            proof_bytes: vec![],
            public_inputs: PublicInputs {
                script_hash: hash_data(b"script"),
                input_hash: hash_data(b"input"),
                output_hash: hash_proof_output(&output),
                gas_consumed: output.gas_consumed,
                execution_success: true,
            },
            vkey_hash: [0u8; 32],
            proof_mode: ProofMode::Mock,
            proof_format_version: PROOF_FORMAT_VERSION,
        };

        assert!(output_matches_public_inputs(&proof));
    }

    #[test]
    fn test_output_mismatch_detected() {
        let output = ProofOutput {
            state: 0,
            result: Some(StackItem::Integer(5)),
            gas_consumed: 42,
            error: None,
        };
        let mut proof = NeoProof {
            output: output.clone(),
            proof_bytes: vec![],
            public_inputs: PublicInputs {
                script_hash: hash_data(b"script"),
                input_hash: hash_data(b"input"),
                output_hash: hash_proof_output(&output),
                gas_consumed: output.gas_consumed,
                execution_success: true,
            },
            vkey_hash: [0u8; 32],
            proof_mode: ProofMode::Mock,
            proof_format_version: PROOF_FORMAT_VERSION,
        };
        proof.output.gas_consumed = proof.output.gas_consumed.saturating_add(1);

        assert!(!output_matches_public_inputs(&proof));
    }

    #[test]
    fn test_compute_commitment_changes_when_inputs_change() {
        let inputs_a = PublicInputs {
            script_hash: [1u8; 32],
            input_hash: [2u8; 32],
            output_hash: [3u8; 32],
            gas_consumed: 10,
            execution_success: true,
        };
        let mut inputs_b = inputs_a.clone();
        inputs_b.gas_consumed = 11;

        assert_ne!(compute_commitment(&inputs_a), compute_commitment(&inputs_b));
    }

    #[test]
    fn test_execute_reports_stack_overflow_for_excessive_arguments() {
        let input = ProofInput {
            script: vec![0x40], // RET
            arguments: vec![StackItem::Integer(1); 10_000],
            gas_limit: 1_000_000,
        };

        let output = execute(input);
        assert_eq!(output.state, 1);
        assert!(output
            .error
            .as_deref()
            .unwrap_or_default()
            .contains("Stack overflow"));
    }

    #[test]
    fn test_execute_reports_runtime_fault_error() {
        let input = ProofInput {
            script: vec![0xFF], // Invalid opcode
            arguments: vec![],
            gas_limit: 1_000_000,
        };

        let output = execute(input);
        assert_eq!(output.state, 1);
        assert!(output
            .error
            .as_deref()
            .unwrap_or_default()
            .contains("Invalid opcode"));
    }

    #[test]
    fn test_try_hash_proof_output_rejects_oversized_output() {
        let output = ProofOutput {
            state: 0,
            result: Some(StackItem::ByteString(vec![0u8; 10 * 1024 * 1024 + 1])),
            gas_consumed: 1,
            error: None,
        };
        assert!(try_hash_proof_output(&output).is_err());

        let proof = NeoProof {
            output,
            proof_bytes: vec![],
            public_inputs: PublicInputs {
                script_hash: [0u8; 32],
                input_hash: [0u8; 32],
                output_hash: [0u8; 32],
                gas_consumed: 1,
                execution_success: true,
            },
            vkey_hash: [0u8; 32],
            proof_mode: ProofMode::Mock,
            proof_format_version: PROOF_FORMAT_VERSION,
        };
        assert!(!output_matches_public_inputs(&proof));
    }

    #[test]
    fn test_legacy_neoproof_deserializes_with_default_format_version() {
        #[derive(Serialize)]
        struct LegacyNeoProof {
            output: ProofOutput,
            proof_bytes: Vec<u8>,
            public_inputs: PublicInputs,
            vkey_hash: [u8; 32],
            proof_mode: ProofMode,
        }

        let legacy = LegacyNeoProof {
            output: ProofOutput {
                state: 0,
                result: Some(StackItem::Integer(1)),
                gas_consumed: 1,
                error: None,
            },
            proof_bytes: vec![],
            public_inputs: PublicInputs {
                script_hash: [1u8; 32],
                input_hash: [2u8; 32],
                output_hash: [3u8; 32],
                gas_consumed: 1,
                execution_success: true,
            },
            vkey_hash: [0u8; 32],
            proof_mode: ProofMode::Mock,
        };

        let bytes = bincode_options()
            .serialize(&legacy)
            .expect("legacy serialize");
        let decoded = deserialize_neoproof(&bytes).expect("legacy deserialize should succeed");

        assert_eq!(decoded.proof_format_version, PROOF_FORMAT_VERSION);
    }
}
