use serde::{Deserialize, Serialize};

use super::{ProofMode, ProofOutput, PublicInputs, default_proof_format_version};

/// Proof generated by the prover.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct NeoProof {
    /// Execution output (result, gas, error).
    pub output: ProofOutput,
    /// Serialized cryptographic proof bytes (empty for Execute mode).
    pub proof_bytes: Vec<u8>,
    /// Public inputs committed in the proof.
    pub public_inputs: PublicInputs,
    /// SHA-256 hash of the SP1 verification key (zero for mock/execute).
    pub vkey_hash: [u8; 32],
    /// The proof mode that was actually used.
    pub proof_mode: ProofMode,
    /// Serialization format version for forward compatibility.
    #[serde(default = "default_proof_format_version")]
    pub proof_format_version: u16,
}
